spring.application.name=taskzen
spring.mongodb.uri=mongodb+srv://rishikeshkarkhanis0101_db_user:uoZqXvjIeQWvv6Tw@taskzen-cluster.5bvaswb.mongodb.net/test?retryWrites=true&w=majority&appName=taskzen-cluster
# spring.mongodb.uri=${MONGODB_URI}
server.port=3000